--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/CzechPMDevs/libpmform
build-by-default: true
branches:
- main
projects:
  libpmform:
    path: ""
    model: virion
    type: library
...
